# Generated by Django 5.2.1 on 2025-05-13 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTOdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAG', models.TextField()),
                ('LEVEL', models.TextField(db_column='"LEVEL"')),
                ('CNAME', models.TextField()),
                ('ENAME', models.TextField()),
                ('TOID', models.TextField()),
                ('PARENTID', models.IntegerField(blank=True, null=True)),
                ('pubAnnotation_evidence', models.TextField(blank=True, null=True)),
                ('llm_evidence', models.TextField(blank=True, null=True)),
                ('rice_alterome_evidence', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtodata_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtodata_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RTOdata',
            },
        ),
        migrations.CreateModel(
            name='TraitEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.TextField()),
                ('expert_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traiteval_created', to=settings.AUTH_USER_MODEL)),
                ('trait', models.ForeignKey(db_column='trait_id', on_delete=django.db.models.deletion.CASCADE, related_name='trait_evaluations', to='rice_trait_ontology.rtodata')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traiteval_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trait_evaluation',
                'indexes': [models.Index(fields=['id', 'trait'], name='trait_evalu_id_ce3265_idx')],
            },
        ),
    ]
